//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#define RT_MANIFEST                     24
#define IDD_MAIN                        101
#define IDD_NET                         102
#define IDD_SEND                        103
#define IDD_SEARCH                      104
#define IDD_RECV                        105
#define IDD_CFG                         106
#define IDD_OSEARCH                     107
#define IDI_ICON1                       107
#define IDD_CHAT                        108
#define IDD_ABOUT                       108
#define IDD_CHATROOMS                   109
#define IDD_LOG                         109
#define IDD_SETUPWIZ                    110
#define IDD_WIZ1                        111
#define IDD_WIZ2                        112
#define IDD_WIZ3                        113
#define IDD_WIZ4                        114
#define IDD_CHAT2                       115
#define IDD_CHATCHAN                    115
#define IDD_CHATROOMS2                  116
#define IDD_PASSWD                      117
#define IDD_RND                         118
#define IDD_CHATPRIV                    119
#define IDR_MENU1                       122
#define IDD_CHATROOMCREATE              124
#define IDD_XFERS                       126
#define IDD_RECVQ                       127
#define IDD_ACEDIT                      128
#define IDI_ROOT                        129
#define IDI_PARENT                      131
#define IDI_USER                        132
#define IDI_FILE                        133
#define IDI_DIR                         134
#define IDR_ACCEL1                      138
#define IDI_SEARCH                      139
#define IDI_STOPDL                      140
#define IDI_MOVETOTOP                   141
#define IDI_MOVETOEND                   142
#define IDI_DLNOW                       143
#define IDR_CONTEXTMENUS                144
#define IDI_CLEARIA                     145
#define IDI_CLEARCOMP                   146
#define IDI_CLEARALL                    147
#define IDI_CONNECT                     150
#define IDI_DISCONNECT                  151
#define IDD_PROFILES                    152
#define IDI_FORWARD                     152
#define IDI_BACKWARD                    153
#define IDD_PROFILE_MOD                 154
#define IDD_FILESUBDLG                  161
#define IDI_MORE                        167
#define IDI_CHAT                        168
#define IDI_BROWSE                      169
#define IDI_XFERS                       170
#define IDD_PREFS                       215
#define IDD_PREF_NETWORK                240
#define IDD_PREF_SECURITY               241
#define IDD_PREF_FILES                  242
#define IDD_PREF_CHAT                   243
#define IDD_PREF_BROWSING               244
#define IDD_PREF_NETWORK_A              244
#define IDD_PREF_DISPLAY                245
#define IDD_PREF_FILES_SEND             246
#define IDD_PREF_FILES_RECV             247
#define IDD_PREF_PROFILES               248
#define IDD_PREF_THROTTLE               249
#define IDD_PREF_KEYDIST                250
#define IDD_KEYIMPORTDLG                251
#define IDD_PREF_KEYDIST_PENDING        252
#define IDD_KEYGEN                      253
#define IDD_RNGINIT                     254
#define IDD_PREF_ABOUT                  255
#define IDD_CHPASS                      256
#define IDD_PREF_IDENT                  257
#define IDC_LIST1                       1000
#define IDC_RECTANGLE                   1001
#define IDC_REMOVECONNECTION            1002
#define IDC_ADDCONNECTION               1003
#define IDC_NEWCONNECTION               1004
#define IDC_SEARCH                      1006
#define IDC_LABEL1                      1006
#define IDC_SEARCHTEXT                  1007
#define IDC_LABEL3                      1008
#define IDC_SEARCHRES                   1009
#define IDC_LABEL4                      1009
#define IDC_DL                          1010
#define ID_DOWNLOADFOLDER               1010
#define IDC_LABEL5                      1010
#define IDC_ABORTSEL                    1011
#define IDC_PROGRESS1                   1011
#define IDC_RECVLIST                    1012
#define IDC_LABEL6                      1012
#define IDC_CLEARCOMP                   1013
#define IDC_RECVLISTQ                   1014
#define IDC_PINGINFO                    1014
#define IDC_CLEARCOMP2                  1014
#define IDC_COMBO1                      1014
#define IDC_PING                        1015
#define IDC_REMOVEQUEUE                 1015
#define IDC_STREAM                      1016
#define IDC_CLEARCOMP3                  1016
#define IDC_MOVETOTOP                   1016
#define IDC_SENDLIST                    1017
#define IDC_CONINFO                     1017
#define IDC_MOVETOBOTTOM                1017
#define IDC_DLNOW                       1018
#define IDC_SAVEPATH                    1019
#define IDC_CLEARQUEUE                  1019
#define IDC_FILEPATHLIST                1020
#define IDC_ADDDIR                      1021
#define IDC_RESCAN                      1022
#define IDC_EXTLIST                     1023
#define IDC_RESUME                      1024
#define IDC_NETCONS                     1025
#define IDC_PORT                        1026
#define IDC_UPDPORT                     1027
#define IDC_CURPORT                     1028
#define IDC_MAXSRCHITEMS                1029
#define IDC_MAXSIMULDL                  1030
#define IDC_AUTOCLEAR                   1031
#define IDC_MINCONSPEED                 1032
#define IDC_AUTORESUME                  1032
#define IDC_CONSPEED                    1033
#define IDC_SCANSTATUS                  1034
#define IDC_THROTTLE                    1035
#define IDC_NUMCONUP                    1036
#define IDC_MAXTTL                      1036
#define IDC_REMOVECATCH                 1037
#define IDC_MYTTL                       1037
#define IDC_CONNECTCATCH                1038
#define IDC_NUMSEARCHES                 1038
#define IDC_GETMORE                     1039
#define IDC_OSEARCHES                   1039
#define IDC_CLEAR                       1040
#define IDC_CHECK1                      1040
#define IDC_EDIT1                       1041
#define IDC_CHECK10                     1041
#define IDC_OLDPASS                     1042
#define IDC_HOSTCATCH                   1043
#define IDC_GNETMSGCNT                  1044
#define IDC_EDIT6                       1044
#define IDC_SEARCHCNT                   1045
#define IDC_SEARCHSTATS                 1045
#define IDC_RERRCNT                     1046
#define IDC_DPCNT                       1047
#define IDC_CHATEDIT                    1047
#define IDC_DLCNT                       1048
#define IDC_CHAT                        1048
#define IDC_ULCNT                       1049
#define IDC_CHATTEXT                    1049
#define IDC_NICK                        1051
#define IDC_ROOMLIST                    1052
#define IDC_UPDATE                      1053
#define IDC_CREATE                      1054
#define IDC_EDIT2                       1055
#define IDC_NEWROOM                     1055
#define IDC_ALTNICK                     1056
#define IDC_EDIT4                       1056
#define IDC_NICKREG                     1057
#define IDC_EDIT5                       1057
#define IDC_NICKSTATUS                  1058
#define IDC_SEARCHMONLIST               1059
#define IDC_MINTEXT                     1060
#define IDC_SNFT                        1061
#define IDC_PTF                         1062
#define IDC_MSD                         1063
#define IDC_DQ                          1064
#define IDC_SL1                         1065
#define IDC_SL2                         1066
#define IDC_TK1                         1067
#define IDC_TK2                         1068
#define IDC_NI                          1069
#define IDC_HCT                         1070
#define IDC_GNM                         1071
#define IDC_SLDB                        1072
#define IDC_RE                          1073
#define IDC_DM                          1074
#define IDC_DC                          1075
#define IDC_ULC                         1076
#define IDC_TAB1                        1079
#define IDC_AUTODISCONNECT              1083
#define IDC_MINSPEED                    1084
#define IDC_DIVIDER1                    1086
#define IDC_BROWSE                      1087
#define IDC_KEYGEN                      1088
#define IDC_KEYINFO                     1089
#define IDC_BROWSE2                     1089
#define IDC_RELOADKEY                   1092
#define IDC_NNBOX                       1093
#define IDC_CHPASS                      1093
#define IDC_CRBOX                       1094
#define IDC_LABEL                       1095
#define IDC_ENCFRAME                    1098
#define IDC_ALLOWPRIV                   1099
#define IDC_HELPTEXT                    1100
#define IDC_BROWSEHOSTS                 1102
#define IDC_CHECK2                      1103
#define IDC_CHECK3                      1104
#define IDC_BUTTON1                     1104
#define IDC_GOROOT                      1104
#define IDC_NETSETTINGS                 1104
#define IDC_CHECK4                      1105
#define IDC_GOPARENT                    1105
#define IDC_EDIT3                       1106
#define IDC_DELETE                      1106
#define IDC_CHECK11                     1106
#define IDC_MINUTELABEL                 1107
#define IDC_CLONE                       1107
#define IDC_CHECK12                     1107
#define IDC_FORWARD                     1107
#define IDC_MD5MB                       1108
#define IDC_RENAME                      1108
#define IDC_CHECK13                     1108
#define IDC_SHAMB                       1108
#define IDC_FORWARD2                    1108
#define IDC_CHECK5                      1109
#define IDC_BACK2                       1109
#define IDC_CHECK6                      1110
#define IDC_TREE1                       1110
#define IDC_USERS                       1111
#define IDC_LIMITUL                     1111
#define IDC_CHECK14                     1111
#define IDC_STATUS                      1112
#define IDC_LIMITUL2                    1112
#define IDC_LIMITOB                     1112
#define IDC_CREATECHATROOM              1114
#define IDC_USERSLABEL                  1115
#define IDC_DIVIDER                     1118
#define IDC_CHATROOMS                   1119
#define IDC_CHATROOMSLABEL              1120
#define IDC_BROWSESAVE                  1123
#define IDC_BACK                        1124
#define IDC_CHECK7                      1124
#define IDC_CHECK8                      1125
#define IDC_CHECK9                      1126
#define IDC_ADD                         1128
#define IDC_REMOVE                      1129
#define IDC_RADIO1                      1129
#define IDC_MOVEUP                      1130
#define IDC_RADIO2                      1130
#define IDC_RADIO3                      1131
#define IDC_MOVEDOWN                    1132
#define IDC_RADIO4                      1132
#define IDC_EDIT                        1133
#define IDC_CLEARALL                    1134
#define IDC_IMPORT                      1134
#define IDC_FILEATONCE                  1135
#define IDC_DIRTOALLOW                  1136
#define IDC_MINUTES                     1137
#define IDC_MB                          1138
#define IDC_SAT_INC                     1140
#define IDC_SAT_OUT                     1141
#define IDC_BUTTON2                     1142
#define IDC_LIMITIB                     1143
#define IDC_BUTTON8                     1143
#define IDC_SRESULTLBL                  1144
#define IDC_BUTTON3                     1145
#define IDC_BUTTON4                     1146
#define IDC_BUTTON5                     1147
#define IDC_CHATFONTTEXT                1148
#define IDC_BUTTON7                     1148
#define IDC_BUTTON6                     1149
#define IDC_SRN                         1150
#define IDC_SRP                         1151
#define IDC_SRF                         1152
#define IDC_QUEUEITEMS                  1153
#define IDC_RELOAD                      1154
#define IDC_KEYTEXT                     1155
#define IDC_VIEWKEYS                    1155
#define IDC_KEYINF                      1156
#define IDC_AUTH                        1157
#define IDC_SFB                         1158
#define IDC_TEXT1                       1159
#define IDC_NEWPASS1                    1160
#define IDC_NEWPASS2                    1161
#define IDC_NETSTATUS                   1162
#define IDC_NAMELISTRESIZER             1163
#define IDC_RECT                        1186
#define IDC_UPATH                       19000
#define ID_FILE_QUIT                    40001
#define ID_VIEW_TRANSFERS               40004
#define ID_VIEW_NETWORKCONNECTIONS      40005
#define ID_VIEW_PREFERENCES             40006
#define ID_VIEW_ALWAYSONTOP             40008
#define ID_LAUNCHSEL                    40010
#define ID_DLFOLDER                     40011
#define ID_ABORTSEL                     40012
#define ID_RESUME                       40013
#define ID_PRIVMSGNODE                  40014
#define ID_SENDFILENODE                 40015
#define ID_BROWSELOC                    40016
#define ID_DOWNLOAD                     40017
#define ID_BROWSEUSER                   40018
#define ID_VIEW_MAINWND                 40019
#define ID_SYSTRAY_QUIT                 40020
#define ID_SYSTRAY_SHOW                 40021
#define ID_DLQ_DOWNLOADNOW              40022
#define ID_DLQ_MOVETOTOP                40023
#define ID_DLQ_MOVETOBOTTOM             40024
#define ID_DLQ_REMOVEFROMQUEUE          40025
#define ID_ULWND_ABORTUPLOADS           40027
#define ID_VIEW_TRANSFERS2              40040
#define ID_VIEW_PREFERENCES2            40041
#define ID_VIEW_NETWORKCONNECTIONS2     40042
#define IDC_CREATECHATROOM2             40043
#define IDC_SEARCH2                     40044
#define ID_VIEW_ALWAYSONTOP2            40045
#define ID_VIEW_POOP_NOCHATWINDOWS      40047
#define IDM_ABOUT                       40051
#define ID_BROWSEFOLDER                 40053
#define ID_BROWSENODE                   40054
#define ID_DLPARENT                     40055
#define ID_COPYLOC                      40056
#define ID_CLEANUPDLDIR                 40058
#define ID_WHOISUSER                    40059
#define ID_LAUNCHSEL2                   40060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
