//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by waste.rc
//
#define IDD_MAIN                        101
#define IDD_NET                         102
#define IDD_SEND                        103
#define IDD_SEARCH                      104
#define IDD_RECV                        105
#define IDI_ICON1                       107
#define IDD_SETUPWIZ                    110
#define IDD_WIZ1                        111
#define IDD_WIZ2                        112
#define IDD_WIZ4                        114
#define IDD_CHATCHAN                    115
#define IDD_PASSWD                      117
#define IDD_CHATPRIV                    119
#define IDR_MENU1                       122
#define IDD_CHATROOMCREATE              124
#define IDD_XFERS                       126
#define IDD_RECVQ                       127
#define IDD_ACEDIT                      128
#define IDI_ROOT                        129
#define IDI_PARENT                      131
#define IDI_USER                        132
#define IDI_FILE                        133
#define IDI_DIR                         134
#define IDR_ACCEL1                      138
#define IDI_SEARCH                      139
#define IDI_STOPDL                      140
#define IDI_MOVETOTOP                   141
#define IDI_MOVETOEND                   142
#define IDI_DLNOW                       143
#define IDR_CONTEXTMENUS                144
#define IDI_CLEARIA                     145
#define IDI_CLEARCOMP                   146
#define IDI_CLEARALL                    147
#define IDI_CONNECT                     150
#define IDI_DISCONNECT                  151
#define IDD_PROFILES                    152
#define IDI_FORWARD                     152
#define IDI_BACKWARD                    153
#define IDD_PROFILE_MOD                 154
#define IDD_FILESUBDLG                  161
#define IDI_MORE                        167
#define IDI_CHAT                        168
#define IDI_BROWSE                      169
#define IDI_XFERS                       170
#define IDD_PREF_PERFORM                171
#define IDD_PREF_CHAT                   173
#define IDI_PLAY                        174
#define IDD_PREF_LICENSE                175
#define IDR_METALLICA                   176
#define IDD_PREF_CHAT_B                 177
#define IDC_CURSOR1                     178
#define IDC_HTMLHAND                    178
#define IDD_PREFS                       215
#define IDD_PREF_NETWORK                240
#define IDD_PREF_SECURITY               241
#define IDD_PREF_FILES                  242
#define IDD_PREF_CHAT_A                 243
#define IDD_PREF_NETWORK_A              244
#define IDD_PREF_DISPLAY                245
#define IDD_PREF_FILES_SEND             246
#define IDD_PREF_FILES_RECV             247
#define IDD_PREF_PROFILES               248
#define IDD_PREF_THROTTLE               249
#define IDD_PREF_KEYDIST                250
#define IDD_KEYIMPORTDLG                251
#define IDD_PREF_KEYDIST_PENDING        252
#define IDD_KEYGEN                      253
#define IDD_RNGINIT                     254
#define IDD_PREF_ABOUT                  255
#define IDD_CHPASS                      256
#define IDD_PREF_IDENT                  257
#define IDD_PREF_NETWORK_B              258
#define IDD_PREF_NETWORK_C              259
#define IDC_LIST_PROFILES               1000
#define IDC_RECTANGLE                   1001
#define IDC_REMOVECONNECTION            1002
#define IDC_ADDCONNECTION               1003
#define IDC_NEWCONNECTION               1004
#define IDC_SEARCH                      1006
#define IDC_SEARCHTEXT                  1007
#define IDC_SEARCHRES                   1009
#define ID_DOWNLOADFOLDER               1010
#define IDC_ABORTSEL                    1011
#define IDC_PROGRESS_RNG                1011
#define IDC_RECVLIST                    1012
#define IDC_LABEL_KEYSIZE               1012
#define IDC_CLEARCOMP                   1013
#define IDC_RECVLISTQ                   1014
#define IDC_CLEARCOMP2                  1014
#define IDC_COMBO_KEYSIZE               1014
#define IDC_REMOVEQUEUE                 1015
#define IDC_CLEARCOMP3                  1016
#define IDC_MOVETOTOP                   1016
#define IDC_SENDLIST                    1017
#define IDC_MOVETOBOTTOM                1017
#define IDC_DLNOW                       1018
#define IDC_SAVEPATH                    1019
#define IDC_CLEARQUEUE                  1019
#define IDC_FILEPATHLIST                1020
#define IDC_ADDDIR                      1021
#define IDC_RESCAN                      1022
#define IDC_EDIT_EXTLIST                1023
#define IDC_RESUME                      1024
#define IDC_NETCONS                     1025
#define IDC_PORT                        1026
#define IDC_UPDPORT                     1027
#define IDC_CURPORT                     1028
#define IDC_EDIT_LIMIT_IN_HO            1029
#define IDC_MAXSIMULDL                  1030
#define IDC_EDIT_LIMIT_IN               1030
#define IDC_AUTOCLEAR                   1031
#define IDC_AUTORESUME                  1032
#define IDC_CONSPEED                    1033
#define IDC_SCANSTATUS                  1034
#define IDC_NUMCONUP                    1036
#define IDC_REMOVECATCH                 1037
#define IDC_CONNECTCATCH                1038
#define IDC_CHECK_SAVE_PASSWD           1040
#define IDC_CHECK_SHOW_PARTIAL_UPLOADPATH 1041
#define IDC_OLDPASS                     1042
#define IDC_CHAT_ALLOW_BCAST            1042
#define IDC_EDIT_NETPASSWORD            1044
#define IDC_SEARCHSTATS                 1045
#define IDC_CHATEDIT                    1047
#define IDC_CHAT                        1048
#define IDC_CHATTEXT                    1049
#define IDC_CREATE                      1054
#define IDC_CHAT_FLASH_USER_EDIT        1056
#define IDC_EDIT_CLIENTID               1056
#define IDC_CHAT_FLASH_ROOM_EDIT        1057
#define IDC_NICKSTATUS                  1058
#define IDC_CHAT_FLASH_BCAST_EDIT       1058
#define IDC_SNFT                        1061
#define IDC_PTF                         1062
#define IDC_MSD                         1063
#define IDC_TK1                         1067
#define IDC_TK2                         1068
#define IDC_TAB1                        1079
#define IDC_BUTTON_IMPORT_KEY           1087
#define IDC_KEYGEN                      1088
#define IDC_KEYINFO                     1089
#define IDC_BUTTON_EXPORT_PKEY          1089
#define IDC_BUTTON_CHECKBLIND           1090
#define IDC_RELOADKEY                   1092
#define IDC_CHPASS                      1093
#define IDC_ENCFRAME                    1098
#define IDC_CHECK_LIMIT_INBOUND         1103
#define IDC_GOROOT                      1104
#define IDC_NETSETTINGS                 1104
#define IDC_BUTTON_RUN_KEYGEN           1104
#define IDC_CHECK_USE_ACL               1104
#define IDC_GOPARENT                    1105
#define IDC_CHECK_DISPLAY_TRANSFER_ON_DL 1105
#define IDC_DELETE                      1106
#define IDC_CHECK_USE_PATH_ON_REC_DL    1106
#define IDC_EDIT_RESCAN_MINUTES         1106
#define IDC_CLONE                       1107
#define IDC_FORWARD                     1107
#define IDC_CHECK_USE_PATH_ON_REC_DL_SEARCH 1107
#define IDC_RENAME                      1108
#define IDC_SHAMB                       1108
#define IDC_FORWARD2                    1108
#define IDC_CHECK_USE_PATH_ON_REC_DL_BROWSED 1108
#define IDC_BACK2                       1109
#define IDC_CHECK_FOCUS_TRANSFER_ON_DL  1109
#define IDC_CHECK_DISPLAY_TRANSFER_ON_UL 1110
#define IDC_TREE_CHATROOM               1110
#define IDC_USERS                       1111
#define IDC_CHECK_DL_PARENTPATH_ON_REC  1111
#define IDC_EDIT_LIMIT_UL               1111
#define IDC_STATUS                      1112
#define IDC_EDIT_LIMIT_OUTBOUND         1112
#define IDC_CREATECHATROOM              1114
#define IDC_USERSLABEL                  1115
#define IDC_DIVIDER                     1118
#define IDC_CHATROOMS                   1119
#define IDC_CHATROOMSLABEL              1120
#define IDC_BROWSESAVE                  1123
#define IDC_BACK                        1124
#define IDC_CHECK_FOCUS_TRANSFER_ON_UL  1124
#define IDC_CHECK_DISPLAY_TRANSFER_ON_DL_BY_REMOTEINIT 1125
#define IDC_CHECK_FOCUS_TRANSFER_ON_DL_BY_REMOTEINIT 1126
#define IDC_DOWNLOAD_ONCE               1127
#define IDC_CHAT_FLASH_BCAST_STOP       1127
#define IDC_BUTTON_ADD                  1128
#define IDC_REMOVE                      1129
#define IDC_RADIO_ALLOW_ACCESS          1129
#define IDC_BUTTON_MOVEUP               1130
#define IDC_RADIO_DENY_ACCESS           1130
#define IDC_RADIO_LIMIT_OUTBOUND_PER_CONN 1131
#define IDC_BUTTON_MOVEDOWN             1132
#define IDC_RADIO_LIMIT_OUTBOUND_PER_TOTAL 1132
#define IDC_BUTTON_EDIT                 1133
#define IDC_CLEARALL                    1134
#define IDC_IMPORT                      1134
#define IDC_SAT_INC                     1140
#define IDC_SAT_OUT                     1141
#define IDC_BUTTON_RENEW_CLIENTID       1143
#define IDC_BUTTON_BROADCAST_PUB        1143
#define IDC_EDIT_LIMIT_INBOUND          1143
#define IDC_SRESULTLBL                  1144
#define IDC_BUTTON_FONT                 1145
#define IDC_BUTTON_USERLIST_BACKCOLOR   1146
#define IDC_BUTTON_BACK                 1147
#define IDC_CHATFONTTEXT                1148
#define IDC_BUTTON_USERLIST_TEXTCOLOR   1148
#define IDC_CHAT_BOX_COLOR_FONT         1149
#define IDC_RADIO_SRN                   1150
#define IDC_BUTTON_OTHERS               1150
#define IDC_RADIO_SRP                   1151
#define IDC_RADIO_SRF                   1152
#define IDC_QUEUEITEMS                  1153
#define IDC_RELOAD                      1154
#define IDC_KEYTEXT                     1155
#define IDC_VIEWKEYS                    1155
#define IDC_KEYINF                      1156
#define IDC_AUTH                        1157
#define IDC_SFB                         1158
#define IDC_TEXT_VERSION                1159
#define IDC_NEWPASS1                    1160
#define IDC_NEWPASS2                    1161
#define IDC_NETSTATUS                   1162
#define IDC_NAMELISTRESIZER             1163
#define IDC_ENABLELOG                   1164
#define IDC_EDITLOGLOCATION             1165
#define IDC_BUTTONLOGLOCATION           1166
#define IDC_STATUSLOGERROR              1167
#define IDC_PERFORMS                    1168
#define IDC_EDITLOGLEVEL                1168
#define IDC_CHECK_LOG_ROOM              1168
#define IDC_BUTTONLOGFLUSH              1169
#define IDC_CHAT_BOX_COLOR_BACK         1169
#define IDC_CHECK_LOG_BCAST             1169
#define IDC_CHAT_ALLOW_USER             1170
#define IDC_ENABLEIMMEDIATEFLUSH        1170
#define IDC_CHAT_FLASH_USER             1171
#define IDC_CHAT_FLASH_USER_STOP        1172
#define IDC_CHAT_FLASH_ROOM             1173
#define IDC_CHAT_FLASH_ROOM_STOP        1174
#define IDC_CHAT_STAMP_USER             1175
#define IDC_CHAT_STAMP_ROOM             1176
#define IDC_CHAT_STAMP_DATED            1177
#define IDC_CHAT_FLASH_BCAST            1178
#define IDC_CHAT_LIMIT                  1179
#define IDC_CHAT_HIDEONMIN              1180
#define IDC_CHAT_LIMIT_EDIT             1181
#define IDC_CHAT_BOX_COLOR_OTHERS       1182
#define IDC_RADIO_IP_NORMAL             1183
#define IDC_RADIO_IP_FORCED             1184
#define IDC_RADIO_IP_AUTO               1185
#define IDC_RECT                        1186
#define IDC_EDIT_FORCEIP                1186
#define IDC_EDIT_SHOW_RESOLVE           1187
#define IDC_EDIT_SHOW_CURRENTIP         1188
#define IDC_CHECK_DIRECT_XFER           1188
#define IDC_CHECK_NICK_ON_XFER          1189
#define IDC_CHECK_DIRECT_XFER_CONNECT   1190
#define IDC_EDIT_NETWORK_NAME           1191
#define IDC_CHECK_PREAUTH               1192
#define IDC_BUTTON_PREAUTH_HELP         1194
#define IDC_CHECK_ROUTE                 1195
#define IDC_CHECK_LISTEN                1196
#define IDC_CHECK_ADVERTISE             1197
#define IDC_CHECK_LIMIT_IN              1198
#define IDC_CHECK_CHAT_SOUND            1198
#define IDC_CHECK_LIMIT_IN_HO           1199
#define IDC_EDIT_CHAT_SOUND_FILENAME    1199
#define IDC_BUTTON_CHAT_SOUND_BROWSE    1200
#define IDC_BUTTON_CHAT_SOUND_PLAY      1201
#define IDC_EDIT_LICENSE                1202
#define IDC_EDIT_NICK                   1203
#define IDC_BUTTON_UPDATE_NICK          1204
#define IDC_EDIT_USERNAME               1205
#define IDC_BUTTON_COPY_PUBKEY          1206
#define IDC_BUTTON_IMPORT_PKEY          1207
#define IDC_CHECK_PERIODIC_BCAST        1208
#define IDC_EDIT_SHOW_PKHASH            1209
#define IDC_CHECK_DISPLAY_IN_TRAY       1210
#define IDC_CHECK_TRAY_AUTOHIDE         1211
#define IDC_CHECK_DISPLAY_AS_TOOLWIN    1212
#define IDC_CHECK_CONFIRM_EXIT          1213
#define IDC_CHECK_HIDE_ALL_ON_MIN       1214
#define IDC_CHECK_SAVE_BROWSE_MRU       1215
#define IDC_CHECK_SHOW_DIAGNOSTIC_INFOS 1216
#define IDC_BUTTON_START_PROFILE_MANAGER 1217
#define IDC_CHECK_SHOW_PROFILEMAN_ON_START 1218
#define IDC_CHECK_APPEND_PRIFILE_NAME   1219
#define IDC_CHECK_REBROADCAST_KEYS      1220
#define IDC_CHECK_AUTO_ACCEPT_KEYS      1221
#define IDC_CHECK_PROMPT_ON_NEW_KEY     1222
#define IDC_LIST_PENDING_KEYS           1223
#define IDC_LIST_PUBLIC_KEYS            1224
#define IDC_LIST_ACL                    1225
#define IDC_CHECK_ALLOW_UPLOADING       1226
#define IDC_CHECK_QUERY_ON_UPLOAD       1227
#define IDC_CHECK_UPLOAD_USE_RELPATHS   1228
#define IDC_CHECK_LIMIT_DL              1229
#define IDC_CHECK_DL_PARENTPATH_ON_SEARCH 1230
#define IDC_CHECK_DL_PARENTPATH_ON_BROWSED 1231
#define IDC_EDIT_DL_PATH                1232
#define IDC_EDIT_LIMIT_DL               1233
#define IDC_CHECK_LIMIT_UL              1234
#define IDC_CHECK_INDEX_FILES           1235
#define IDC_CHECK_LIMIT_EXTENSIONS      1236
#define IDC_CHECK_AUTORESCAN            1237
#define IDC_CHECK_CACHE_ON_EXIT         1238
#define IDC_CHECK_RESCAN_ON_START       1239
#define IDC_CHECK_SHA_FILES             1240
#define IDC_CHECK_DL_ALLOW_SEARCH       1241
#define IDC_CHECK_DL_ALLOW_BROWSE       1242
#define IDC_BUTTON_LOAD_KEYTEXT         1243
#define IDC_BUTTON_IMPORT_PUBKEYS       1244
#define IDC_CHECK_LIMIT_OUTBOUND        1245
#define IDC_RADIO_LIMIT_INBOUND_PER_CONN 1246
#define IDC_RADIO_LIMIT_INBOUND_PER_TOTAL 1247
#define IDC_BUTTON_REMOVE               1248
#define IDC_EDIT_PASSWORD               1249
#define IDC_EDIT_PASSWORD_AGAIN         1250
#define IDC_PROGRESS_KEYGEN             1251
#define IDC_LABEL_LINE1                 1252
#define IDC_LABEL_LINE2                 1253
#define IDC_LABEL_PASSWORD              1254
#define IDC_LABEL_PASSWORD_AGAIN        1255
#define IDC_EDIT_PROFILENAME            1256
#define IDC_EDIT_SOURCENAME             1257
#define IDC_EDIT_DESTNAME               1258
#define IDC_EDIT_IP_AND_MASK            1259
#define IDC_EDIT_FILTER                 1260
#define IDC_EDIT_CHATROOMNAME           1261
#define IDC_TREE_PREFERENCES            1262
#define IDC_BUTTON_CLIENTID_HELP        1263
#define IDC_TEXT_CRIGHT                 1264
#define IDC_CHECK_LOG_PM                1265
#define IDC_LABEL_PASSWDED              1266
#define IDC_HOMEPAGE                    1267
#define IDC_CREDITS                     1268
#define IDC_BUTTON1                     1269
#define IDC_LICENSE_GBOX                1270
#define IDC_EDIT1                       1271
#define IDC_UPATH                       19000
#define ID_FILE_QUIT                    40001
#define ID_VIEW_TRANSFERS               40004
#define ID_VIEW_NETWORKCONNECTIONS      40005
#define ID_VIEW_PREFERENCES             40006
#define ID_VIEW_ALWAYSONTOP             40008
#define ID_LAUNCHSEL                    40010
#define ID_DLFOLDER                     40011
#define ID_ABORTSEL                     40012
#define ID_RESUME                       40013
#define ID_PRIVMSGNODE                  40014
#define ID_SENDFILENODE                 40015
#define ID_BROWSELOC                    40016
#define ID_DOWNLOAD                     40017
#define ID_BROWSEUSER                   40018
#define ID_VIEW_MAINWND                 40019
#define ID_VIEW_TRANSFERS2              40040
#define ID_VIEW_PREFERENCES2            40041
#define ID_VIEW_NETWORKCONNECTIONS2     40042
#define IDC_CREATECHATROOM2             40043
#define IDC_SEARCH2                     40044
#define ID_VIEW_ALWAYSONTOP2            40045
#define ID_VIEW_POOP_NOCHATWINDOWS      40047
#define ID_BROWSEFOLDER                 40053
#define ID_BROWSENODE                   40054
#define ID_DLPARENT                     40055
#define ID_COPYLOC                      40056
#define ID_CLEANUPDLDIR                 40058
#define ID_WHOISUSER                    40059
#define ID_LAUNCHSEL2                   40060
#define ID_CLEANUPSELECTED              57680

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         1272
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
